services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - stagingAws.env
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    command: go run ./cmd/server/main.go
volumes:
  postgres:
